repos:
  # Official repo for default hooks
  - repo: https://github.com/precice/precice-pre-commit-hooks
    rev: "v3.3"
    hooks:
      - id: format-precice-config
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.30.0
    hooks:
      - id: markdownlint
        exclude: "CHANGELOG.md|.github/*"
      - id: markdownlint-fix
        exclude: "CHANGELOG.md|.github/*"
  # clang-format for C/C++ formatting
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v19.1.2
    hooks:
      - id: clang-format
        args: ["--style=file"]
        types_or: [c++]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-xml
      - id: check-merge-conflict
      - id: mixed-line-ending
      - id: end-of-file-fixer
      - id: trailing-whitespace
  # black repo for python formatting
  - repo: https://github.com/ambv/black
    rev: 25.1.0
    hooks:
      - id: black
        name: format python
