site_name: DuMuX-preCICE adapter

theme:
  name: 'material'
  palette:
    primary: deep orange
    accent: blue

repo_name: dumux-appl/dumux-preCICE
repo_url: https://github.com/precice/dumux-adapter

markdown_extensions:
  - admonition

