name: Build and test
on: [pull_request, push]

jobs:
  build-and-test-code:
    strategy:
      matrix:
        dumux_version: [3.4, 3.5, master]
        precice_version: [2.3.0, 2.4.0]
        exclude:
        - dumux_version: master
          precice_version: 2.3.0
    runs-on: ubuntu-latest
    container:
      image: ajaust/dumux-precice:${{ matrix.dumux_version }}-${{ matrix.precice_version }}
    steps:
    - name: Check out code
      uses: actions/checkout@v3
      with:
        path: dumux-precice
    - name: Build code
      run: |
        ls -lah
        export DUNE_CONTROL_PATH=${PWD}/dumux-precice:${DUNE_CONTROL_PATH}
        echo $DUNE_CONTROL_PATH
        dunecontrol --only=dumux-precice --opts=./dumux-precice/test/cmake-test.opts all
        cd dumux-precice/build-cmake/
        make -j2 build_tests