name: Build and upload Docker containers

on:
  workflow_dispatch:
  push:
    branches:
      - develop

jobs:
  build-and-release-docker-image:
    name: Builds a Docker container for testing the DuMuX preCICE adapter
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dumux_version: [3.4, 3.5, master]
        precice_version: [2.3.0, 2.4.0]
        #dumux_version: [3.5]
        #precice_version: [2.4.0]
        exclude:
        - dumux_version: master
          precice_version: 2.3.0
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Dockerfile
        uses: docker/build-push-action@v2
        with:
          push: true
          file: "./docker/dockerfile.slim"
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/dumux-precice:${{ matrix.dumux_version }}-${{ matrix.precice_version }}
          build-args: |
            DUNE_VERSION=2.8
            PRECICEUBUNTU=focal
            DUMUX_VERSION=${{ matrix.dumux_version }}
            PRECICE_VERSION=${{ matrix.precice_version }}
