name: Build and test (DuMuX master)
on:
  pull_request:
  push:
    branches:
      - develop
      - main

jobs:
  build-and-test-dumux-master:
    strategy:
      max-parallel: 1
      matrix:
        dumux_version: [master]
        precice_version: [2.4.0, 2.5.0]
        dune_version: [2.8]
    container:
      image: ajaust/dune-precice:${{ matrix.dune_version }}-${{ matrix.precice_version }}
    runs-on: ubuntu-latest
    steps:
    - name: Print python3 version
      run: python3 --version
    - name: Print python3 version (/usr/bin/env python3)
      run: /usr/bin/env python3 --version
    - name: Build DuMuX master
      run: |
        ls -lah
        git clone --depth 1 https://git.iws.uni-stuttgart.de/dumux-repositories/dumux.git -b master
        ls -lah
        export DUNE_CONTROL_PATH=${DUNE_CONTROL_PATH}:${PWD}/dumux/dune.module
        dunecontrol --opts=/opt/DUMUX/cmake-test.opts --only=dumux all
    - name: Check out code
      uses: actions/checkout@v3
      with:
        path: dumux-precice
    - name: Build code
      run: |
        ls -lah
        export DUNE_CONTROL_PATH=${PWD}/dumux:${PWD}/dumux-precice:${DUNE_CONTROL_PATH}
        echo $DUNE_CONTROL_PATH
        dunecontrol --only=dumux-precice --opts=./dumux-precice/test/cmake-test.opts all
        cd dumux-precice/build-cmake/
        make -j2 build_tests
    - name: Run tests
      run: |
        export DUNE_CONTROL_PATH=${PWD}/dumux:${PWD}/dumux-precice:${DUNE_CONTROL_PATH}
        cd dumux-precice/build-cmake/
        export PYTHONPATH=${PWD}/dumux/bin/testing:${PYTHONPATH}
        CTEST_OUTPUT_ON_FAILURE=1 ctest -j1
