name: Style checking
on:
  pull_request:
  push:
    branches:
      - develop
      - main

jobs:
  pre_commit_checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout preCICE
        uses: actions/checkout@v5
      - name: Setup python
        uses: actions/setup-python@v5
        with:
         python-version: '3.10'
         check-latest: true
      - name: Install pre-commit
        run: pip install pre-commit
      - name: Run checks
        run: pre-commit run -a -v
      - name: Git status
        if: always()
        run: git status
      - name: Full diff
        if: always()
        run: git diff
  python_linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10.10'
      - name: "Install style checker"
        run: pip install --user black~=22.12
      - name: "Run style check"
        run: black --check .
  cpp_linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Run format check
        run: |
          sudo apt-get install clang-format-14
          ./scripts/format/run-clang-format.sh
